# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name icfoxleme.dev;

    ssl_certificate /etc/nginx/certs/icfoxleme.dev+1.pem;
    ssl_certificate_key /etc/nginx/certs/icfoxleme.dev+1-key.pem;

    root /var/www/react/;
    index index.htm index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    #client_max_body_size 100M;
}

# HTTP
server {
    listen 80 http2;
    listen [::]:80 http2;
    server_name icfoxleme.dev;
    return 301 https://$host$request_uri;

    root /var/www/react/;
    index index.htm index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    #client_max_body_size 100M;
}

